overblog_graphql:
    definitions:
        config_validation: "%kernel.debug%"
        show_debug_info: "%graphql_show_debug_info%"
        schema:
            query: Query
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
