jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    # metadata:
        # directories:
            # FOSUserBundle:
                # path: '%kernel.project_dir%/serializer/FOSUserBundle'
                # namespace_prefix: 'FOS\UserBundle\Model'
