RootQuery:
    type: object
    config:
        description: "Events Queries"
        fields:
            event:
                type: "Event"
                access: "@=hasRole('ROLE_EVENT_SHOW')"
                args:
                    id:
                        description: "Resolves using the Event ID."
                        type: "ID!"
                resolve: "@=resolver('Event', [args])"
            events_list:
                type: "EventsList"
                access: "@=hasRole('ROLE_EVENTS_LIST')"
                args:
                    page:
                        description: "Page number"
                        type: "Int"
                    limit:
                        description: "Limit items per page"
                        type: "Int"
                resolve: "@=resolver('EventsList', [args])"
